---
job1:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - cd /home/bitrix/ext_www/dev.site.tld/
    - git checkout develop
    - git commit -am "Autocommit of the local changes from develop" || true
    - git pull --strategy=recursive -X ours origin develop
    - git push origin develop || true
  only:
    - develop
  tags:
    - site.tld-dev
job2:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - cd /home/bitrix/www/
    - git checkout master
    # Examples of autocommit the local changes made by clients
    - git commit -am "Autocommit of the local changes from master" || true
    - git pull --strategy=recursive -X ours origin master
    - git push origin master || true
    # This dir should exist in dev branch, but not in master
    - rm -rf local/demo/
    - git ls-files -z local/demo/ | xargs -0 git update-index --skip-worktree
  only:
    - master
  tags:
    - site.tld-master
