---
job1:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - cd /home/bitrix/ext_www/dev.site.tld/
    - git checkout develop
    - git fetch origin develop
    - git pull origin develop
  only:
    - develop
  tags:
    - site.tld-dev
job2:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - cd /home/bitrix/www/
    - git checkout master
    # Examples of autocommit the local changes made by clients
    - git add .
    - git commit -m "Autocommit of the local changes" || true
    - git push origin master || true
    - git pull origin master
    # This dir should exist in dev branch, but not in master
    - rm -rf local/demo/
    - git ls-files -z local/demo/ | xargs -0 git update-index --skip-worktree
  only:
    - master
  tags:
    - site.tld-master
