
---
# https://hub.docker.com/r/gitlab/gitlab-ce/tags
# mkdir -p /srv/gitlab/{config,logs,data}
version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:14.8.2-ce.0'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://git.example.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2289
        gitlab_rails['time_zone'] = 'Europe/Moscow'
        # backup
        gitlab_rails['backup_keep_time'] = 172800
        # mail
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.yandex.ru"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "info@example.com"
        gitlab_rails['smtp_password'] = "pass"
        gitlab_rails['smtp_domain'] = "example.com"
        gitlab_rails['smtp_authentication'] = "plain"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_ssl'] = false
        gitlab_rails['smtp_force_ssl'] = false
        gitlab_rails['gitlab_email_from'] = 'info@example.com'
        gitlab_rails['gitlab_email_reply_to'] = 'info@example.com'
    ports:
      - '8929:80'
      - '2289:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
