---
# playbook.yml file.
# ansible all -i localhost, -m debug -a "msg={{ 'mypass' | password_hash('sha512') }}"
- hosts: bitrix
  become: yes
  tasks:
   - name: Ensure group "sftp" exists
     group:
      name: sftp
      state: present
   - name: Ensure user "{{ item.user }}" exists
      user:
       name: "{{ item.user }}"
       uid: 600
       group: bitrix
       groups: sftp
       non_unique: yes
       create_home: no
       home: /home/bitrix
       password: "{{ item.pass }}"
       #state: absent
       #force: yes
      loop:
      - user: 'aorza'
        pass: "{{ 'pass1' | password_hash('sha512') }}"
      - user: 'dkarikh'
        pass: "{{ 'pass1' | password_hash('sha512') }}"
      - user: 'nhovzunov'
        pass: "{{ 'pass1' | password_hash('sha512') }}"
      - user: 'karikh'
        pass: "{{ 'pass1' | password_hash('sha512') }}"
